// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract SimpleStorage {
    string public message;

    // Set an initial message when deploying
    constructor(string memory _message) {
        message = _message;
    }

    // Update the stored message
    function setMessage(string memory _message) public {
        message = _message;
    }

    // Read the stored message (getter is auto-generated by Solidity, but we can still add one)
    function getMessage() public view returns (string memory) {
        return message;
    }
}
